### PR TITLE
[146] Working cookies

### PR DESCRIPTION
**Pull request by Szyntos**
Added session management with cookies.

There are some issues though.

1. IDK if user context is necessary now, we're always fetching the user from the cookies afaik, @AnCichocka plz check
2. Refreshing while on HallOfFame view breaks this view. This is because it fetches data before the user is set by userContext. Imo this view needs to wait for this data, or not throw an error, but render anything - when the user will load it would refresh with the correct data
3. Log out does not refresh the welcome screen data, i.e. when I'm logged in as a student i see only teachers and myself in the Welcome screen, and when I log out i should see everyone, but i still see only the teachers. This changes after refresh because the data is fetched again. This screen also stores the edition from the logged out user, which leads to errors. This need to be fixed, @AnCichocka could ya?

### CODE REVIEW

**Comment by AnCichocka** [comment]
2. the problem is not useUser context, the problem is undefined selectedEdition

**Comment by AnCichocka** [comment]
After all not quite working - there were some frontend issues. The one that concerns me the most is caching. Queries are executed in the first time and result data is stored in cache. When cookies changes (which triggers headers change) queries are not executed again and return data for "stale" cookie, for example: 

1. I was logged in as user id 1
2. I logged out
3. I logged in as user id 2 - but I still get data for user id 1, because it uses cache

Solution: `add fetchPolicy: "no-cache"` to every query which requires update - it sounds like a poor solution and we probably will need to figure out something else or for now even resign for caching and add it globally in apollo client?

**Comment by AnCichocka** [comment]
I think we should stick to user context, I simplifies a lot of error handling

**Comment by AnCichocka** [comment]
@Szyntos I get user is not participating in this edition error after logout and login on different user - headers and cookies seem to be correctly set. After page refresh everything works correctly. I think it might be a problem connected to now() - 1?

**Comment by Szyntos** [comment]
> @Szyntos I get user is not participating in this edition error after logout and login on different user - headers and cookies seem to be correctly set. After page refresh everything works correctly. I think it might be a problem connected to now() - 1?

I remember telling you about this issue sometime ago. This is because the edition data is not cleared when logging out:

image

on the top right corner you can see that the selected edition is edition=2, yet we should see:

image

no edition selected

-----------------------

when you log in as a different user when the previous edition is selected, you are not querying the new edition, so you have a mismatch

a quick fix should be to clear the selected edition on the logout and always query it on the login, but idk if this is THE solution

**Review by AnCichocka — APPROVED** [review]
Raz sie zyje

**Pull request merged**
