### PR TITLE
[FE-248 FE-255] Delete file, fix undefined levelSet error

### PR DESCRIPTION
**Pull request by AnCichocka**
https://oops2000.atlassian.net/browse/SCRUM-248
https://oops2000.atlassian.net/browse/SCRUM-255

### CODE REVIEW

**Comment by AnCichocka** [comment]
@Szyntos, do we want to block delete buttons?

**Comment by AnCichocka** [comment]
@Szyntos update query to contain permissions

**Comment by Szyntos** [comment]
query Files {
  getFilesGroupedByTypeBySelectedTypes(fileTypes: "image/user") {
    fileType
    files {
      file {
        createdAt
        fileId
        fileName
        fileType
        label
        pathToFile
        updatedAt
      }
      permissions {
        canRemove {
          action
          allow
          arguments
          reason
        }
      }
    }
  }
}

**Comment by AnCichocka** [comment]
@Szyntos corrected :)

**Review by Szyntos — APPROVED** [review]
lgtm <>3

**Pull request merged**
